[
  {
    "keyword": "买11元得33元",
    "schemeUrl": "https://you.163.com/item/detail?id=3986228&keyword=买11元得33元",
    "highlight": 1,
    "hidden": 0,
    "type": 0,
    "algSort": false,
    "extra": {
      "taskId": "54636307",
      "materialId": "54631962",
      "taskType": 1,
      "resourcesId": 2,
      "crmUserGroupId": "0",
      "crmUserGroupName": "",
      "materialName": "买11元得33元",
      "operator": null,
      "itemId": null,
      "materialType": "热搜词id",
      "itemIdList": null,
      "customAdPicUrl": null,
      "customAdLinkUrl": null,
      "schemeUrl": null,
      "itemFrom": 0,
      "materialContentFrom": 1,
      "rcmdSort": false
    }
  },
  {
    "keyword": "免洗面膜仅49.9",
    "schemeUrl": "https://you.163.com/item/detail?id=3465073&keyword=免洗面膜仅49.9",
    "highlight": 0,
    "hidden": 0,
    "type": 0,
    "algSort": false,
    "extra": {
      "taskId": "54634565",
      "materialId": "54631868",
      "taskType": 1,
      "resourcesId": 3,
      "crmUserGroupId": "0",
      "crmUserGroupName": "",
      "materialName": "免洗面膜仅49.9",
      "operator": null,
      "itemId": null,
      "materialType": "热搜词id",
      "itemIdList": null,
      "customAdPicUrl": null,
      "customAdLinkUrl": null,
      "schemeUrl": null,
      "itemFrom": 0,
      "materialContentFrom": 1,
      "rcmdSort": false
    }
  },
  {
    "keyword": "保暖内衣 第2件半价",
    "schemeUrl": "https://act.you.163.com/act/pub/0F57kIa3hMj5.html?keyword=保暖内衣 第2件半价",
    "highlight": 1,
    "hidden": 0,
    "type": 0,
    "algSort": false,
    "extra": {
      "taskId": "54636395",
      "materialId": "54631970",
      "taskType": 1,
      "resourcesId": 7,
      "crmUserGroupId": "0",
      "crmUserGroupName": "无分组",
      "materialName": "保暖内衣 第2件半价",
      "operator": null,
      "itemId": null,
      "materialType": "热搜词id",
      "itemIdList": null,
      "customAdPicUrl": null,
      "customAdLinkUrl": null,
      "schemeUrl": null,
      "itemFrom": 0,
      "materialContentFrom": 1,
      "rcmdSort": false
    }
  },
  {
    "keyword": "时尚按摩筋膜枪",
    "schemeUrl": "https://you.163.com/item/detail?id=3814094&keyword=时尚按摩筋膜枪",
    "highlight": 0,
    "hidden": 0,
    "type": 0,
    "algSort": false,
    "extra": {
      "taskId": "54636273",
      "materialId": "54631901",
      "taskType": 1,
      "resourcesId": 8,
      "crmUserGroupId": "0",
      "crmUserGroupName": "无分组",
      "materialName": "时尚按摩筋膜枪",
      "operator": null,
      "itemId": null,
      "materialType": "热搜词id",
      "itemIdList": null,
      "customAdPicUrl": null,
      "customAdLinkUrl": null,
      "schemeUrl": null,
      "itemFrom": 0,
      "materialContentFrom": 1,
      "rcmdSort": false
    }
  },
  {
    "keyword": "金秋大闸蟹",
    "schemeUrl": "https://you.163.com/item/detail?id=3856014&keyword=金秋大闸蟹",
    "highlight": 0,
    "hidden": 0,
    "type": 0,
    "algSort": false,
    "extra": {
      "taskId": "54636170",
      "materialId": "54631631",
      "taskType": 1,
      "resourcesId": 10,
      "crmUserGroupId": "0",
      "crmUserGroupName": "",
      "materialName": "金秋大闸蟹",
      "operator": null,
      "itemId": null,
      "materialType": "热搜词id",
      "itemIdList": null,
      "customAdPicUrl": null,
      "customAdLinkUrl": null,
      "schemeUrl": null,
      "itemFrom": 0,
      "materialContentFrom": 1,
      "rcmdSort": false
    }
  },
  {
    "keyword": "保温电水壶",
    "schemeUrl": "https://act.you.163.com/act/pub/UrbyY0nhwwx7.html?keyword=保温电水壶",
    "highlight": 0,
    "hidden": 0,
    "type": 0,
    "algSort": false,
    "extra": {
      "taskId": "54636430",
      "materialId": "54631978",
      "taskType": 1,
      "resourcesId": 11,
      "crmUserGroupId": "0",
      "crmUserGroupName": "无分组",
      "materialName": "保温电水壶",
      "operator": null,
      "itemId": null,
      "materialType": "热搜词id",
      "itemIdList": null,
      "customAdPicUrl": null,
      "customAdLinkUrl": null,
      "schemeUrl": null,
      "itemFrom": 0,
      "materialContentFrom": 1,
      "rcmdSort": false
    }
  },
  {
    "keyword": "拖鞋",
    "schemeUrl": null,
    "highlight": 0,
    "hidden": 0,
    "type": 1,
    "algSort": false,
    "extra": null
  },
  {
    "keyword": "保温杯",
    "schemeUrl": null,
    "highlight": 0,
    "hidden": 0,
    "type": 1,
    "algSort": false,
    "extra": null
  },
  {
    "keyword": "猫粮",
    "schemeUrl": null,
    "highlight": 0,
    "hidden": 0,
    "type": 1,
    "algSort": false,
    "extra": null
  },
  {
    "keyword": "四件套",
    "schemeUrl": null,
    "highlight": 0,
    "hidden": 0,
    "type": 1,
    "algSort": false,
    "extra": null
  },
  {
    "keyword": "床垫",
    "schemeUrl": null,
    "highlight": 0,
    "hidden": 0,
    "type": 1,
    "algSort": false,
    "extra": null
  },
  {
    "keyword": "行李箱",
    "schemeUrl": null,
    "highlight": 0,
    "hidden": 0,
    "type": 1,
    "algSort": false,
    "extra": null
  }
]
